# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='id',
        ),
        migrations.AlterField(
            model_name='commit',
            name='hash',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
