# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 04:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='track_editors', to=settings.AUTH_USER_MODEL),
        ),
    ]
